#!/bin/sh

#Display shinanigans
xrandr --dpi 96
setbg &

#swap escape and capslock
setxkbmap -option caps:swapescape

#Autostart
picom &
dunst &
unclutter &
udiskie &
pipewire &
mpd &

#xrdb wait
[ -n "$xrdbpid" ] && wait "$xrdbpid"
